// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEVdYz_GwMZ_Uz7rCCua3gBx-pZLYD8fM',
    appId: '1:260578779074:web:4c442bd80f35a36c1fc05b',
    messagingSenderId: '260578779074',
    projectId: 'speedygo-a13e2',
    authDomain: 'speedygo-a13e2.firebaseapp.com',
    storageBucket: 'speedygo-a13e2.appspot.com',
    measurementId: 'G-9BR557WDJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK-Hp4S3mx6kx3P9GQKmbm-0khAhBvVZY',
    appId: '1:260578779074:android:87769fa292fd45ca1fc05b',
    messagingSenderId: '260578779074',
    projectId: 'speedygo-a13e2',
    storageBucket: 'speedygo-a13e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCULF6eiatHphDmcz0oPYj1B60oKpNOJcU',
    appId: '1:260578779074:ios:b522cc98e6cd0ee31fc05b',
    messagingSenderId: '260578779074',
    projectId: 'speedygo-a13e2',
    storageBucket: 'speedygo-a13e2.appspot.com',
    iosBundleId: 'com.example.speedyGo',
  );
}
