/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData no_internet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData awards = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData awards_2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg, matchTextDirection: true);
  static const IconData behance = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_add = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg, matchTextDirection: true);
  static const IconData events = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gmail = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg, matchTextDirection: true);
  static const IconData login = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shedule = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website_2 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tracks = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData translate = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_2 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer_2 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news_2 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData board = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
